-- =====================================================================
-- _deploy_all.sql  -- Déploiement consolidé ERP_APP / XEPDB1
-- Connexion : sql ERP_APP/Apex2026_Secure@@localhost:1521/XEPDB1
-- =====================================================================
SET DEFINE OFF
WHENEVER SQLERROR CONTINUE

ALTER SESSION SET CURRENT_SCHEMA = ERP_APP;

-- -------------------------------------------------------
-- GUARDS : supprimer les tables existantes (ordre FK inverse)
-- -------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "TES-TRANSFER-RECEPTION" CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "TES-TRANSFER-LINE" CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "TES-TRANSFER" CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "TES-STOCK-SITE" CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "TES-SITE-AUDIT" CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "HQ_VENTES_JOUR" CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "HQ_STOCK_JOUR" CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "HQ_SYNC_LOG" CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "TES-MAGASIN" CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "TES-USER" CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "TES-SITE" CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_transfer_num'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_transfer_num'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

PROMPT ==== Guards DROP OK ====

-- -------------------------------------------------------
-- 01 : DDL Schema multi-sites (10 tables)
-- -------------------------------------------------------

-- 1. Table des sites
CREATE TABLE "TES-SITE" (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SITE_CODE       VARCHAR2(20 CHAR) NOT NULL,
    SITE_NAME       VARCHAR2(200 CHAR) NOT NULL,
    SITE_TYPE       VARCHAR2(30 CHAR) NOT NULL,
    PARENT_SITE_ID  NUMBER,
    ADDRESS         VARCHAR2(255 CHAR),
    CITY            VARCHAR2(100 CHAR),
    ZIP_CODE        VARCHAR2(20 CHAR),
    PHONE           VARCHAR2(30 CHAR),
    EMAIL           VARCHAR2(200 CHAR),
    RESP_NAME       VARCHAR2(200 CHAR),
    ACTIVE          VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL,
    DATCRE          DATE DEFAULT SYSDATE NOT NULL,
    DATMOD          DATE,
    CONSTRAINT uk_tes_site_code UNIQUE (SITE_CODE),
    CONSTRAINT ck_tes_site_type CHECK (SITE_TYPE IN ('HEAD_OFFICE','DEPOT_PRINCIPAL','DEPOT_SM','SUPERMARKET')),
    CONSTRAINT ck_tes_site_active CHECK (ACTIVE IN ('Y','N'))
);

COMMENT ON TABLE "TES-SITE" IS 'Référentiel des sites de la chaîne (HQ, dépôts, supermarchés)';
CREATE INDEX idx_tes_site_type   ON "TES-SITE"(SITE_TYPE);
CREATE INDEX idx_tes_site_parent ON "TES-SITE"(PARENT_SITE_ID);

-- 2. Table des magasins
CREATE TABLE "TES-MAGASIN" (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SITE_ID         NUMBER NOT NULL,
    MAGASIN_CODE    VARCHAR2(20 CHAR) NOT NULL,
    MAGASIN_NAME    VARCHAR2(200 CHAR) NOT NULL,
    MAGASIN_TYPE    VARCHAR2(30 CHAR) DEFAULT 'PRINCIPAL',
    CASHIER_COUNT   NUMBER DEFAULT 1,
    POS_COUNT       NUMBER DEFAULT 1,
    ACTIVE          VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL,
    DATCRE          DATE DEFAULT SYSDATE NOT NULL,
    DATMOD          DATE,
    CONSTRAINT uk_tes_magasin_code UNIQUE (MAGASIN_CODE),
    CONSTRAINT fk_tes_magasin_site FOREIGN KEY (SITE_ID) REFERENCES "TES-SITE"(ID)
);

-- 3. Stock par site
CREATE TABLE "TES-STOCK-SITE" (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SITE_ID         NUMBER NOT NULL,
    CODART          VARCHAR2(80 CHAR) NOT NULL,
    QTEPHYSIQUE     NUMBER(16,4) DEFAULT 0,
    QTETHEORIQUE    NUMBER(16,4) DEFAULT 0,
    QTEMIN          NUMBER(16,4),
    QTEMAX          NUMBER(16,4),
    QTESEC          NUMBER(16,4),
    QTECOMMANDE     NUMBER(16,4) DEFAULT 0,
    QTEENTRANSIT    NUMBER(16,4) DEFAULT 0,
    DERNIER_MVT     DATE,
    DATCRE          DATE DEFAULT SYSDATE NOT NULL,
    DATMOD          DATE,
    CONSTRAINT uk_tes_stock_site UNIQUE (SITE_ID, CODART),
    CONSTRAINT fk_tes_stock_site_site FOREIGN KEY (SITE_ID) REFERENCES "TES-SITE"(ID)
);

CREATE INDEX idx_tes_stock_site_codart  ON "TES-STOCK-SITE"(CODART);
CREATE INDEX idx_tes_stock_site_alerte  ON "TES-STOCK-SITE"(SITE_ID, QTEMIN, QTEPHYSIQUE);

-- 4. Transferts inter-sites
CREATE TABLE "TES-TRANSFER" (
    ID                   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRANSFER_NUM         VARCHAR2(20 CHAR) NOT NULL,
    SITE_SOURCE_ID       NUMBER NOT NULL,
    SITE_DEST_ID         NUMBER NOT NULL,
    DATDEMANDE           DATE DEFAULT SYSDATE NOT NULL,
    DATENVOI_SOUHAITEE   DATE,
    DATRECEPT_SOUHAITEE  DATE,
    DATENVOI_EFFECTIVE   DATE,
    DATRECEPT_EFFECTIVE  DATE,
    ETAT                 VARCHAR2(30 CHAR) DEFAULT 'DEMANDE' NOT NULL,
    PRIORITY             VARCHAR2(20 CHAR) DEFAULT 'NORMALE' NOT NULL,
    TRANSPORT_MODE       VARCHAR2(30 CHAR),
    NUM_BORDEREAU        VARCHAR2(30 CHAR),
    CUTI_DEMANDE         VARCHAR2(20 CHAR),
    CUTI_ENVOI           VARCHAR2(20 CHAR),
    CUTI_RECEPT          VARCHAR2(20 CHAR),
    COMMENTAIRE_DEMANDE  VARCHAR2(1000 CHAR),
    COMMENTAIRE_ENVOI    VARCHAR2(1000 CHAR),
    COMMENTAIRE_RECEPT   VARCHAR2(1000 CHAR),
    DATCRE               DATE DEFAULT SYSDATE NOT NULL,
    DATMOD               DATE,
    CONSTRAINT uk_tes_transfer_num  UNIQUE (TRANSFER_NUM),
    CONSTRAINT fk_tes_transfer_src  FOREIGN KEY (SITE_SOURCE_ID) REFERENCES "TES-SITE"(ID),
    CONSTRAINT fk_tes_transfer_dst  FOREIGN KEY (SITE_DEST_ID)   REFERENCES "TES-SITE"(ID),
    CONSTRAINT ck_tes_transfer_etat CHECK (ETAT IN (
        'DEMANDE','VALIDE','EN_PREPARATION','EN_TRANSIT','RECEPTIONNE','CLOTURE','ANNULE')),
    CONSTRAINT ck_tes_transfer_priority CHECK (PRIORITY IN ('NORMALE','URGENTE','CRITIQUE'))
);

CREATE INDEX idx_tes_transfer_etat      ON "TES-TRANSFER"(ETAT);
CREATE INDEX idx_tes_transfer_src       ON "TES-TRANSFER"(SITE_SOURCE_ID);
CREATE INDEX idx_tes_transfer_dst       ON "TES-TRANSFER"(SITE_DEST_ID);
CREATE INDEX idx_tes_transfer_datdemande ON "TES-TRANSFER"(DATDEMANDE DESC);

-- 5. Lignes de transfert
CREATE TABLE "TES-TRANSFER-LINE" (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRANSFER_ID     NUMBER NOT NULL,
    NUMLIG          NUMBER NOT NULL,
    CODART          VARCHAR2(80 CHAR) NOT NULL,
    QTEDEMANDEE     NUMBER(16,4) NOT NULL,
    QTEPREPAREE     NUMBER(16,4) DEFAULT 0,
    QTEEXPEDIEE     NUMBER(16,4) DEFAULT 0,
    QTERECEPTIONNEE NUMBER(16,4) DEFAULT 0,
    PRIX_UNITAIRE   NUMBER(16,4),
    COMMENTAIRE     VARCHAR2(500 CHAR),
    DATCRE          DATE DEFAULT SYSDATE NOT NULL,
    DATMOD          DATE,
    CONSTRAINT uk_tes_transfer_line UNIQUE (TRANSFER_ID, NUMLIG),
    CONSTRAINT fk_tes_transfer_line FOREIGN KEY (TRANSFER_ID) REFERENCES "TES-TRANSFER"(ID) ON DELETE CASCADE
);

CREATE INDEX idx_tes_transfer_line_art ON "TES-TRANSFER-LINE"(CODART);

-- 6. Réception signée
CREATE TABLE "TES-TRANSFER-RECEPTION" (
    ID               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRANSFER_ID      NUMBER NOT NULL,
    DATRECEPTION     DATE DEFAULT SYSDATE NOT NULL,
    RECEPTIONNE_PAR  VARCHAR2(200 CHAR) NOT NULL,
    ETAT_RECEPTION   VARCHAR2(30 CHAR) DEFAULT 'CONFORME' NOT NULL,
    NB_COLIS_ATTENDUS NUMBER,
    NB_COLIS_RECUS    NUMBER,
    COMMENTAIRE      VARCHAR2(1000 CHAR),
    DATCRE           DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uk_tes_reception_transfer UNIQUE (TRANSFER_ID),
    CONSTRAINT fk_tes_reception_transfer FOREIGN KEY (TRANSFER_ID) REFERENCES "TES-TRANSFER"(ID),
    CONSTRAINT ck_tes_reception_etat CHECK (ETAT_RECEPTION IN ('CONFORME','PARTIELLE','NON_CONFORME','ENDOMMAGE'))
);

-- 7. Audit log
CREATE TABLE "TES-SITE-AUDIT" (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SITE_ID         NUMBER,
    AUDIT_TYPE      VARCHAR2(50 CHAR) NOT NULL,
    ENTITY_TABLE    VARCHAR2(50 CHAR),
    ENTITY_ID       NUMBER,
    ACTION          VARCHAR2(50 CHAR),
    USER_NAME       VARCHAR2(200 CHAR),
    DETAILS         VARCHAR2(4000 CHAR),
    AUDIT_DATETIME  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_tes_audit_site ON "TES-SITE-AUDIT"(SITE_ID);
CREATE INDEX idx_tes_audit_dt   ON "TES-SITE-AUDIT"(AUDIT_DATETIME DESC);

-- 8. Users multi-tenant (cohérent avec 05_authz_site_ctx.sql)
CREATE TABLE "TES-USER" (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME        VARCHAR2(100 CHAR) NOT NULL,
    USER_FULLNAME   VARCHAR2(400 CHAR),
    EMAIL           VARCHAR2(200 CHAR),
    SITE_ID         NUMBER NOT NULL,
    USER_ROLE       VARCHAR2(30 CHAR) DEFAULT 'SM_USER' NOT NULL,
    ACTIVE          VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL,
    DATCRE          DATE DEFAULT SYSDATE NOT NULL,
    DATMOD          DATE,
    CONSTRAINT uk_tes_user_name UNIQUE (USERNAME),
    CONSTRAINT fk_tes_user_site FOREIGN KEY (SITE_ID) REFERENCES "TES-SITE"(ID),
    CONSTRAINT ck_tes_user_role CHECK (USER_ROLE IN ('HQ_ADMIN','SM_MANAGER','SM_USER','DEPOT_USER'))
);

CREATE INDEX idx_tes_user_site ON "TES-USER"(SITE_ID);

-- 9. Agrégation ventes journalières
CREATE TABLE "HQ_VENTES_JOUR" (
    JOUR            DATE NOT NULL,
    SITE_ID         NUMBER NOT NULL,
    NUMTICKETS      NUMBER DEFAULT 0,
    TOTAL_HT        NUMBER(18,4) DEFAULT 0,
    TOTAL_TTC       NUMBER(18,4) DEFAULT 0,
    TOTAL_REMISE    NUMBER(18,4) DEFAULT 0,
    TOTAL_NET       NUMBER(18,4) DEFAULT 0,
    MONTANT_ESPECES NUMBER(18,4) DEFAULT 0,
    MONTANT_CB      NUMBER(18,4) DEFAULT 0,
    MONTANT_CHEQUE  NUMBER(18,4) DEFAULT 0,
    MONTANT_AUTRE   NUMBER(18,4) DEFAULT 0,
    DATCRE          DATE DEFAULT SYSDATE,
    CONSTRAINT pk_hq_ventes_jour PRIMARY KEY (JOUR, SITE_ID),
    CONSTRAINT fk_hq_ventes_site FOREIGN KEY (SITE_ID) REFERENCES "TES-SITE"(ID)
);

CREATE INDEX idx_hq_ventes_site ON "HQ_VENTES_JOUR"(SITE_ID);

-- 10. Photo stock journalier
CREATE TABLE "HQ_STOCK_JOUR" (
    JOUR        DATE NOT NULL,
    SITE_ID     NUMBER NOT NULL,
    CODART      VARCHAR2(80 CHAR) NOT NULL,
    QTEPHYSIQUE NUMBER(16,4),
    QTETHEORIQUE NUMBER(16,4),
    VALEUR_PRMP NUMBER(18,4),
    DATCRE      DATE DEFAULT SYSDATE,
    CONSTRAINT pk_hq_stock_jour PRIMARY KEY (JOUR, SITE_ID, CODART),
    CONSTRAINT fk_hq_stock_site FOREIGN KEY (SITE_ID) REFERENCES "TES-SITE"(ID)
);

CREATE INDEX idx_hq_stock_site_codart ON "HQ_STOCK_JOUR"(SITE_ID, CODART);

-- 11. Log synchronisation HQ
CREATE TABLE "HQ_SYNC_LOG" (
    ID                NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SYNC_DATETIME     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    SITE_ID           NUMBER,
    SYNC_TYPE         VARCHAR2(50 CHAR) NOT NULL,
    SYNC_STATUS       VARCHAR2(20 CHAR) NOT NULL,
    RECORDS_PROCESSED NUMBER DEFAULT 0,
    RECORDS_FAILED    NUMBER DEFAULT 0,
    ERROR_MESSAGE     VARCHAR2(4000 CHAR),
    DETAILS           CLOB,
    CONSTRAINT fk_hq_sync_site FOREIGN KEY (SITE_ID) REFERENCES "TES-SITE"(ID)
);

CREATE INDEX idx_hq_sync_dt     ON "HQ_SYNC_LOG"(SYNC_DATETIME DESC);
CREATE INDEX idx_hq_sync_status ON "HQ_SYNC_LOG"(SYNC_STATUS);

-- Séquence numérotation transferts
CREATE SEQUENCE seq_transfer_num START WITH 1 INCREMENT BY 1 NOCACHE;

-- Trigger auto-numérotation
CREATE OR REPLACE TRIGGER trg_transfer_num
BEFORE INSERT ON "TES-TRANSFER"
FOR EACH ROW
WHEN (NEW.TRANSFER_NUM IS NULL)
DECLARE
    v_prefix VARCHAR2(10);
    v_seq    NUMBER;
BEGIN
    SELECT SUBSTR(SITE_CODE, 1, 3) INTO v_prefix FROM "TES-SITE" WHERE ID = :NEW.SITE_SOURCE_ID;
    :NEW.TRANSFER_NUM := v_prefix || '-' || TO_CHAR(SYSDATE, 'YYYYMMDD') || '-' || LPAD(seq_transfer_num.NEXTVAL, 5, '0');
END;
/

PROMPT ==== 01_schema : 11 tables + sequence + trigger OK ====

-- -------------------------------------------------------
-- 02 : Seed — 11 sites + magasins
-- -------------------------------------------------------

-- HQ
INSERT INTO "TES-SITE" (SITE_CODE, SITE_NAME, SITE_TYPE, PARENT_SITE_ID, ADDRESS, CITY, ZIP_CODE, PHONE, EMAIL, RESP_NAME)
VALUES ('HQ', 'Siège Principal', 'HEAD_OFFICE', NULL,
        '15 rue de la Direction', 'Paris', '75001', '+33145001111', 'siege@retailchain.com', 'DG Directeur');

-- Dépôt principal
INSERT INTO "TES-SITE" (SITE_CODE, SITE_NAME, SITE_TYPE, PARENT_SITE_ID, ADDRESS, CITY, ZIP_CODE, PHONE, EMAIL, RESP_NAME)
VALUES ('DEP_P', 'Dépôt Principal Île-de-France', 'DEPOT_PRINCIPAL',
        (SELECT ID FROM "TES-SITE" WHERE SITE_CODE='HQ'),
        'Zone industrielle 4', 'Roissy', '95700', '+33145002222', 'depot.p@retailchain.com', 'Chef Dépôt Principal');

-- SM1 + son dépôt
INSERT INTO "TES-SITE" (SITE_CODE, SITE_NAME, SITE_TYPE, PARENT_SITE_ID, CITY, RESP_NAME) VALUES
    ('DEP_SM1', 'Dépôt SM1', 'DEPOT_SM', (SELECT ID FROM "TES-SITE" WHERE SITE_CODE='DEP_P'), 'Lyon', 'Chef Dépôt SM1');
INSERT INTO "TES-SITE" (SITE_CODE, SITE_NAME, SITE_TYPE, PARENT_SITE_ID, CITY, ADDRESS, RESP_NAME) VALUES
    ('SM1', 'Supermarché Lyon Centre', 'SUPERMARKET',
     (SELECT ID FROM "TES-SITE" WHERE SITE_CODE='DEP_SM1'), 'Lyon', '12 place Bellecour', 'Manager SM1');

-- SM2 + son dépôt
INSERT INTO "TES-SITE" (SITE_CODE, SITE_NAME, SITE_TYPE, PARENT_SITE_ID, CITY, RESP_NAME) VALUES
    ('DEP_SM2', 'Dépôt SM2', 'DEPOT_SM', (SELECT ID FROM "TES-SITE" WHERE SITE_CODE='DEP_P'), 'Marseille', 'Chef Dépôt SM2');
INSERT INTO "TES-SITE" (SITE_CODE, SITE_NAME, SITE_TYPE, PARENT_SITE_ID, CITY, ADDRESS, RESP_NAME) VALUES
    ('SM2', 'Supermarché Marseille Prado', 'SUPERMARKET',
     (SELECT ID FROM "TES-SITE" WHERE SITE_CODE='DEP_SM2'), 'Marseille', '34 avenue du Prado', 'Manager SM2');

-- SM3 + son dépôt
INSERT INTO "TES-SITE" (SITE_CODE, SITE_NAME, SITE_TYPE, PARENT_SITE_ID, CITY, RESP_NAME) VALUES
    ('DEP_SM3', 'Dépôt SM3', 'DEPOT_SM', (SELECT ID FROM "TES-SITE" WHERE SITE_CODE='DEP_P'), 'Bordeaux', 'Chef Dépôt SM3');
INSERT INTO "TES-SITE" (SITE_CODE, SITE_NAME, SITE_TYPE, PARENT_SITE_ID, CITY, ADDRESS, RESP_NAME) VALUES
    ('SM3', 'Supermarché Bordeaux Sainte-Catherine', 'SUPERMARKET',
     (SELECT ID FROM "TES-SITE" WHERE SITE_CODE='DEP_SM3'), 'Bordeaux', '56 rue Sainte-Catherine', 'Manager SM3');

-- SM4 + son dépôt
INSERT INTO "TES-SITE" (SITE_CODE, SITE_NAME, SITE_TYPE, PARENT_SITE_ID, CITY, RESP_NAME) VALUES
    ('DEP_SM4', 'Dépôt SM4', 'DEPOT_SM', (SELECT ID FROM "TES-SITE" WHERE SITE_CODE='DEP_P'), 'Lille', 'Chef Dépôt SM4');
INSERT INTO "TES-SITE" (SITE_CODE, SITE_NAME, SITE_TYPE, PARENT_SITE_ID, CITY, ADDRESS, RESP_NAME) VALUES
    ('SM4', 'Supermarché Lille Euralille', 'SUPERMARKET',
     (SELECT ID FROM "TES-SITE" WHERE SITE_CODE='DEP_SM4'), 'Lille', 'Avenue Willy Brandt', 'Manager SM4');

-- SM5 + son dépôt
INSERT INTO "TES-SITE" (SITE_CODE, SITE_NAME, SITE_TYPE, PARENT_SITE_ID, CITY, RESP_NAME) VALUES
    ('DEP_SM5', 'Dépôt SM5', 'DEPOT_SM', (SELECT ID FROM "TES-SITE" WHERE SITE_CODE='DEP_P'), 'Nantes', 'Chef Dépôt SM5');
INSERT INTO "TES-SITE" (SITE_CODE, SITE_NAME, SITE_TYPE, PARENT_SITE_ID, CITY, ADDRESS, RESP_NAME) VALUES
    ('SM5', 'Supermarché Nantes Atlantis', 'SUPERMARKET',
     (SELECT ID FROM "TES-SITE" WHERE SITE_CODE='DEP_SM5'), 'Nantes', 'Centre Commercial Atlantis', 'Manager SM5');

-- Magasins (caisses par supermarché)
INSERT INTO "TES-MAGASIN" (SITE_ID, MAGASIN_CODE, MAGASIN_NAME, CASHIER_COUNT, POS_COUNT)
SELECT ID, SITE_CODE || '-CAISSE-1', SITE_NAME || ' - Caisse Principale', 1, 1
FROM "TES-SITE" WHERE SITE_TYPE='SUPERMARKET';

INSERT INTO "TES-MAGASIN" (SITE_ID, MAGASIN_CODE, MAGASIN_NAME, CASHIER_COUNT, POS_COUNT)
SELECT ID, SITE_CODE || '-CAISSE-2', SITE_NAME || ' - Caisse Secondaire', 1, 1
FROM "TES-SITE" WHERE SITE_TYPE='SUPERMARKET';

INSERT INTO "TES-MAGASIN" (SITE_ID, MAGASIN_CODE, MAGASIN_NAME, CASHIER_COUNT, POS_COUNT)
SELECT ID, 'HQ-CAISSE-1', 'Siège - Bureau Achats', 1, 0
FROM "TES-SITE" WHERE SITE_CODE='HQ';

-- Users de test (cohérent avec 05_authz_site_ctx.sql)
INSERT INTO "TES-USER" (USERNAME, USER_FULLNAME, EMAIL, SITE_ID, USER_ROLE) VALUES
    ('admin',        'Administrateur HQ',         'admin@retailchain.com',         (SELECT ID FROM "TES-SITE" WHERE SITE_CODE='HQ'),    'HQ_ADMIN');
INSERT INTO "TES-USER" (USERNAME, USER_FULLNAME, EMAIL, SITE_ID, USER_ROLE) VALUES
    ('manager_sm1',  'Manager Supermarché SM1',  'sm1.manager@retailchain.com',   (SELECT ID FROM "TES-SITE" WHERE SITE_CODE='SM1'),  'SM_MANAGER');
INSERT INTO "TES-USER" (USERNAME, USER_FULLNAME, EMAIL, SITE_ID, USER_ROLE) VALUES
    ('caissier_sm1', 'Caissier SM1',              'sm1.caissier@retailchain.com',  (SELECT ID FROM "TES-SITE" WHERE SITE_CODE='SM1'),  'SM_USER');
INSERT INTO "TES-USER" (USERNAME, USER_FULLNAME, EMAIL, SITE_ID, USER_ROLE) VALUES
    ('depot_p',      'Chef Dépôt Principal',     'depot.p@retailchain.com',       (SELECT ID FROM "TES-SITE" WHERE SITE_CODE='DEP_P'), 'DEPOT_USER');

-- Stock initial de démonstration (quelques articles par site)
DECLARE
    CURSOR c_sites IS SELECT ID, SITE_CODE FROM "TES-SITE" WHERE SITE_TYPE IN ('SUPERMARKET','DEPOT_PRINCIPAL','DEPOT_SM');
    v_articles  SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST('ART0001','ART0002','ART0003','ART0004','ART0005','ART0006','ART0007','ART0008','ART0009','ART0010');
BEGIN
    FOR s IN c_sites LOOP
        FOR i IN 1 .. v_articles.COUNT LOOP
            INSERT INTO "TES-STOCK-SITE"
                (SITE_ID, CODART, QTEPHYSIQUE, QTETHEORIQUE, QTEMIN, QTEMAX, QTESEC, DERNIER_MVT)
            VALUES
                (s.ID, v_articles(i),
                 ROUND(DBMS_RANDOM.VALUE(0, 500), 2),
                 ROUND(DBMS_RANDOM.VALUE(0, 500), 2),
                 10, 600, 20, SYSDATE - ROUND(DBMS_RANDOM.VALUE(0, 30)));
        END LOOP;
    END LOOP;
END;
/

-- Transferts de démonstration
DECLARE
    v_src NUMBER;
    v_dst NUMBER;
BEGIN
    SELECT ID INTO v_src FROM "TES-SITE" WHERE SITE_CODE='DEP_P';
    SELECT ID INTO v_dst FROM "TES-SITE" WHERE SITE_CODE='SM1';
    INSERT INTO "TES-TRANSFER"
        (TRANSFER_NUM, SITE_SOURCE_ID, SITE_DEST_ID, DATDEMANDE, ETAT, PRIORITY, CUTI_DEMANDE, COMMENTAIRE_DEMANDE)
    VALUES ('DEP-20260919-00001', v_src, v_dst, SYSDATE-2, 'EN_TRANSIT', 'URGENTE', 'manager_sm1', 'Réappro urgente ART0001');
    INSERT INTO "TES-TRANSFER-LINE"
        (TRANSFER_ID, NUMLIG, CODART, QTEDEMANDEE, QTEPREPAREE, QTEEXPEDIEE)
    VALUES (seq_transfer_num.CURRVAL, 1, 'ART0001', 100, 100, 100);
END;
/

-- Log de synchronisation de démonstration
INSERT INTO "HQ_SYNC_LOG" (SYNC_TYPE, SYNC_STATUS, SITE_ID, RECORDS_PROCESSED, RECORDS_FAILED)
VALUES ('TRANSFERT_INTEGRATION', 'SUCCESS', (SELECT ID FROM "TES-SITE" WHERE SITE_CODE='SM1'), 45, 0);

INSERT INTO "HQ_SYNC_LOG" (SYNC_TYPE, SYNC_STATUS, SITE_ID, RECORDS_PROCESSED, RECORDS_FAILED)
VALUES ('TRANSFERT_INTEGRATION', 'SUCCESS', (SELECT ID FROM "TES-SITE" WHERE SITE_CODE='SM2'), 38, 0);

INSERT INTO "HQ_SYNC_LOG" (SYNC_TYPE, SYNC_STATUS, SITE_ID, RECORDS_PROCESSED, RECORDS_FAILED, ERROR_MESSAGE)
VALUES ('REST_POST', 'FAILED', (SELECT ID FROM "TES-SITE" WHERE SITE_CODE='SM3'), 0, 1, 'Connection timeout ORDS SM3');

-- Ventes de démonstration dans HQ_VENTES_JOUR
DECLARE
    CURSOR c_sm IS SELECT ID FROM "TES-SITE" WHERE SITE_TYPE='SUPERMARKET';
BEGIN
    FOR s IN c_sm LOOP
        FOR j IN 0..6 LOOP
            BEGIN
                INSERT INTO "HQ_VENTES_JOUR"
                    (JOUR, SITE_ID, NUMTICKETS, TOTAL_HT, TOTAL_TTC, TOTAL_NET)
                VALUES
                    (TRUNC(SYSDATE)-j, s.ID,
                     ROUND(DBMS_RANDOM.VALUE(80,300)),
                     ROUND(DBMS_RANDOM.VALUE(5000,40000),2),
                     ROUND(DBMS_RANDOM.VALUE(6000,48000),2),
                     ROUND(DBMS_RANDOM.VALUE(5500,46000),2));
            EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
            END;
        END LOOP;
    END LOOP;
END;
/

COMMIT;

PROMPT
PROMPT ====================================================================
PROMPT  Seed OK : sites + magasins + stock demo + transferts + logs + ventes
SELECT SITE_CODE, SITE_TYPE, CITY FROM "TES-SITE" ORDER BY ID;
PROMPT ====================================================================
