CONNECT ERP_APP/"Apex2026_Secure@"@//localhost:1521/XEPDB1
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "TES-USER" CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
@blueprints/05_authz_site_ctx.sql
EXIT
